services:
  # IDP
  keycloak:
    image: keycloak/keycloak:latest
    command: start --import-realm
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    environment:
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      # KC_HOSTNAME_STRICT: false
      # KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db/keycloak
      KC_DB_USER: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_HTTP_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
    volumes:
      - ./docker/idp/realm.json:/opt/keycloak/data/import/realm.json
    restart: always
    networks:
      - idp
      - exposed

  keycloak-db:
    image: postgres:17
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KEYCLOAK_DB_USER:-keycloak}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "keycloak",
          "-U",
          "${KONG_DB_USER:-keycloak}",
        ]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    restart: always
    networks:
      - idp

  # Gateway
  krakend:
    image: krakend:latest
    ports:
      - "80:8080"
    volumes:
      - ./docker/gateway/krakend.json:/etc/krakend/krakend.json
    networks:
      - exposed
      - gateway

  kafka:
    image: apache/kafka:latest
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
    expose:
      - 9092
    restart: always
    networks:
      - pawcare
      - queue

  accounts:
    build:
      context: .
      dockerfile: ./services/account/Dockerfile
    environment:
      PAWCARE_DB_HOST: mongo
      PAWCARE_DB_PORT: 27017
      PAWCARE_DB_USER: ${DB_USER}
      PAWCARE_DB_PASS: ${DB_PASS}
      PAWCARE_CERTS_ENDPOINT: ${KEYCLOAK_HOSTNAME}/realms/pawcare/protocol/openid-connect/certs
      PAWCARE_INSECURE_SKIP_VERIFY: true
    restart: always
    networks:
      - pawcare
      - gateway

  medical:
    build:
      context: .
      dockerfile: ./services/medical/Dockerfile
    environment:
      PAWCARE_DB_HOST: mongo
      PAWCARE_DB_PORT: 27017
      PAWCARE_DB_USER: ${DB_USER}
      PAWCARE_DB_PASS: ${DB_PASS}
      PAWCARE_CERTS_ENDPOINT: ${KEYCLOAK_HOSTNAME}/realms/pawcare/protocol/openid-connect/certs
      PAWCARE_INSECURE_SKIP_VERIFY: true
      PAWCARE_PET_SERVICE_HOST: accounts:81
    restart: always
    networks:
      - pawcare
      - gateway

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - pawcare
      - database

networks:
  gateway:
    driver: bridge
  pawcare:
    driver: bridge
  idp:
    driver: bridge
  queue:
    driver: bridge
  exposed:
    driver: bridge
  database:
    driver: bridge

volumes:
  kong_prefix:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kong_tmp:
    driver_opts:
      type: tmpfs
      device: tmpfs
  keycloak_data:
    driver: local
  kong_data:
    driver: local
  mongo_data:
    driver: local
