// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsErrorResponse models error response
//
// swagger:model models.ErrorResponse
type ModelsErrorResponse struct {

	// error
	Error string `json:"error,omitempty"`

	// request id
	RequestID string `json:"request_id,omitempty"`
}

// Validate validates this models error response
func (m *ModelsErrorResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models error response based on context it is used
func (m *ModelsErrorResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsErrorResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsErrorResponse) UnmarshalBinary(b []byte) error {
	var res ModelsErrorResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
