// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Owner owner
//
// swagger:model Owner
type Owner struct {

	// date of birth
	DateOfBirth string `json:"date_of_birth,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// picture
	Picture string `json:"picture,omitempty"`
}

// Validate validates this owner
func (m *Owner) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this owner based on context it is used
func (m *Owner) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Owner) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Owner) UnmarshalBinary(b []byte) error {
	var res Owner
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
