// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "github.com/dreadster3/pawcare/shared/models/profile"
)

// GetAPIV1ProfilesPetsReader is a Reader for the GetAPIV1ProfilesPets structure.
type GetAPIV1ProfilesPetsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1ProfilesPetsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1ProfilesPetsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAPIV1ProfilesPetsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1ProfilesPetsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/profiles/pets] GetAPIV1ProfilesPets", response, response.Code())
	}
}

// NewGetAPIV1ProfilesPetsOK creates a GetAPIV1ProfilesPetsOK with default headers values
func NewGetAPIV1ProfilesPetsOK() *GetAPIV1ProfilesPetsOK {
	return &GetAPIV1ProfilesPetsOK{}
}

/*
GetAPIV1ProfilesPetsOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIV1ProfilesPetsOK struct {
	Payload []*models.ModelsPet
}

// IsSuccess returns true when this get Api v1 profiles pets o k response has a 2xx status code
func (o *GetAPIV1ProfilesPetsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 profiles pets o k response has a 3xx status code
func (o *GetAPIV1ProfilesPetsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 profiles pets o k response has a 4xx status code
func (o *GetAPIV1ProfilesPetsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 profiles pets o k response has a 5xx status code
func (o *GetAPIV1ProfilesPetsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 profiles pets o k response a status code equal to that given
func (o *GetAPIV1ProfilesPetsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 profiles pets o k response
func (o *GetAPIV1ProfilesPetsOK) Code() int {
	return 200
}

func (o *GetAPIV1ProfilesPetsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/pets][%d] getApiV1ProfilesPetsOK %s", 200, payload)
}

func (o *GetAPIV1ProfilesPetsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/pets][%d] getApiV1ProfilesPetsOK %s", 200, payload)
}

func (o *GetAPIV1ProfilesPetsOK) GetPayload() []*models.ModelsPet {
	return o.Payload
}

func (o *GetAPIV1ProfilesPetsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1ProfilesPetsUnauthorized creates a GetAPIV1ProfilesPetsUnauthorized with default headers values
func NewGetAPIV1ProfilesPetsUnauthorized() *GetAPIV1ProfilesPetsUnauthorized {
	return &GetAPIV1ProfilesPetsUnauthorized{}
}

/*
GetAPIV1ProfilesPetsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAPIV1ProfilesPetsUnauthorized struct {
	Payload *models.ModelsErrorResponse
}

// IsSuccess returns true when this get Api v1 profiles pets unauthorized response has a 2xx status code
func (o *GetAPIV1ProfilesPetsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 profiles pets unauthorized response has a 3xx status code
func (o *GetAPIV1ProfilesPetsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 profiles pets unauthorized response has a 4xx status code
func (o *GetAPIV1ProfilesPetsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 profiles pets unauthorized response has a 5xx status code
func (o *GetAPIV1ProfilesPetsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 profiles pets unauthorized response a status code equal to that given
func (o *GetAPIV1ProfilesPetsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get Api v1 profiles pets unauthorized response
func (o *GetAPIV1ProfilesPetsUnauthorized) Code() int {
	return 401
}

func (o *GetAPIV1ProfilesPetsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/pets][%d] getApiV1ProfilesPetsUnauthorized %s", 401, payload)
}

func (o *GetAPIV1ProfilesPetsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/pets][%d] getApiV1ProfilesPetsUnauthorized %s", 401, payload)
}

func (o *GetAPIV1ProfilesPetsUnauthorized) GetPayload() *models.ModelsErrorResponse {
	return o.Payload
}

func (o *GetAPIV1ProfilesPetsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1ProfilesPetsInternalServerError creates a GetAPIV1ProfilesPetsInternalServerError with default headers values
func NewGetAPIV1ProfilesPetsInternalServerError() *GetAPIV1ProfilesPetsInternalServerError {
	return &GetAPIV1ProfilesPetsInternalServerError{}
}

/*
GetAPIV1ProfilesPetsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetAPIV1ProfilesPetsInternalServerError struct {
	Payload *models.ModelsErrorResponse
}

// IsSuccess returns true when this get Api v1 profiles pets internal server error response has a 2xx status code
func (o *GetAPIV1ProfilesPetsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 profiles pets internal server error response has a 3xx status code
func (o *GetAPIV1ProfilesPetsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 profiles pets internal server error response has a 4xx status code
func (o *GetAPIV1ProfilesPetsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 profiles pets internal server error response has a 5xx status code
func (o *GetAPIV1ProfilesPetsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 profiles pets internal server error response a status code equal to that given
func (o *GetAPIV1ProfilesPetsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 profiles pets internal server error response
func (o *GetAPIV1ProfilesPetsInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1ProfilesPetsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/pets][%d] getApiV1ProfilesPetsInternalServerError %s", 500, payload)
}

func (o *GetAPIV1ProfilesPetsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/pets][%d] getApiV1ProfilesPetsInternalServerError %s", 500, payload)
}

func (o *GetAPIV1ProfilesPetsInternalServerError) GetPayload() *models.ModelsErrorResponse {
	return o.Payload
}

func (o *GetAPIV1ProfilesPetsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
