// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "github.com/dreadster3/pawcare/shared/models/profile"
)

// GetAPIV1ProfilesPetsIDReader is a Reader for the GetAPIV1ProfilesPetsID structure.
type GetAPIV1ProfilesPetsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1ProfilesPetsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1ProfilesPetsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV1ProfilesPetsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAPIV1ProfilesPetsIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV1ProfilesPetsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1ProfilesPetsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/profiles/pets/{id}] GetAPIV1ProfilesPetsID", response, response.Code())
	}
}

// NewGetAPIV1ProfilesPetsIDOK creates a GetAPIV1ProfilesPetsIDOK with default headers values
func NewGetAPIV1ProfilesPetsIDOK() *GetAPIV1ProfilesPetsIDOK {
	return &GetAPIV1ProfilesPetsIDOK{}
}

/*
GetAPIV1ProfilesPetsIDOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIV1ProfilesPetsIDOK struct {
	Payload *models.ModelsPet
}

// IsSuccess returns true when this get Api v1 profiles pets Id o k response has a 2xx status code
func (o *GetAPIV1ProfilesPetsIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 profiles pets Id o k response has a 3xx status code
func (o *GetAPIV1ProfilesPetsIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 profiles pets Id o k response has a 4xx status code
func (o *GetAPIV1ProfilesPetsIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 profiles pets Id o k response has a 5xx status code
func (o *GetAPIV1ProfilesPetsIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 profiles pets Id o k response a status code equal to that given
func (o *GetAPIV1ProfilesPetsIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 profiles pets Id o k response
func (o *GetAPIV1ProfilesPetsIDOK) Code() int {
	return 200
}

func (o *GetAPIV1ProfilesPetsIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/pets/{id}][%d] getApiV1ProfilesPetsIdOK %s", 200, payload)
}

func (o *GetAPIV1ProfilesPetsIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/pets/{id}][%d] getApiV1ProfilesPetsIdOK %s", 200, payload)
}

func (o *GetAPIV1ProfilesPetsIDOK) GetPayload() *models.ModelsPet {
	return o.Payload
}

func (o *GetAPIV1ProfilesPetsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsPet)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1ProfilesPetsIDBadRequest creates a GetAPIV1ProfilesPetsIDBadRequest with default headers values
func NewGetAPIV1ProfilesPetsIDBadRequest() *GetAPIV1ProfilesPetsIDBadRequest {
	return &GetAPIV1ProfilesPetsIDBadRequest{}
}

/*
GetAPIV1ProfilesPetsIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetAPIV1ProfilesPetsIDBadRequest struct {
	Payload *models.ModelsErrorResponse
}

// IsSuccess returns true when this get Api v1 profiles pets Id bad request response has a 2xx status code
func (o *GetAPIV1ProfilesPetsIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 profiles pets Id bad request response has a 3xx status code
func (o *GetAPIV1ProfilesPetsIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 profiles pets Id bad request response has a 4xx status code
func (o *GetAPIV1ProfilesPetsIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 profiles pets Id bad request response has a 5xx status code
func (o *GetAPIV1ProfilesPetsIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 profiles pets Id bad request response a status code equal to that given
func (o *GetAPIV1ProfilesPetsIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get Api v1 profiles pets Id bad request response
func (o *GetAPIV1ProfilesPetsIDBadRequest) Code() int {
	return 400
}

func (o *GetAPIV1ProfilesPetsIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/pets/{id}][%d] getApiV1ProfilesPetsIdBadRequest %s", 400, payload)
}

func (o *GetAPIV1ProfilesPetsIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/pets/{id}][%d] getApiV1ProfilesPetsIdBadRequest %s", 400, payload)
}

func (o *GetAPIV1ProfilesPetsIDBadRequest) GetPayload() *models.ModelsErrorResponse {
	return o.Payload
}

func (o *GetAPIV1ProfilesPetsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1ProfilesPetsIDUnauthorized creates a GetAPIV1ProfilesPetsIDUnauthorized with default headers values
func NewGetAPIV1ProfilesPetsIDUnauthorized() *GetAPIV1ProfilesPetsIDUnauthorized {
	return &GetAPIV1ProfilesPetsIDUnauthorized{}
}

/*
GetAPIV1ProfilesPetsIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAPIV1ProfilesPetsIDUnauthorized struct {
	Payload *models.ModelsErrorResponse
}

// IsSuccess returns true when this get Api v1 profiles pets Id unauthorized response has a 2xx status code
func (o *GetAPIV1ProfilesPetsIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 profiles pets Id unauthorized response has a 3xx status code
func (o *GetAPIV1ProfilesPetsIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 profiles pets Id unauthorized response has a 4xx status code
func (o *GetAPIV1ProfilesPetsIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 profiles pets Id unauthorized response has a 5xx status code
func (o *GetAPIV1ProfilesPetsIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 profiles pets Id unauthorized response a status code equal to that given
func (o *GetAPIV1ProfilesPetsIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get Api v1 profiles pets Id unauthorized response
func (o *GetAPIV1ProfilesPetsIDUnauthorized) Code() int {
	return 401
}

func (o *GetAPIV1ProfilesPetsIDUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/pets/{id}][%d] getApiV1ProfilesPetsIdUnauthorized %s", 401, payload)
}

func (o *GetAPIV1ProfilesPetsIDUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/pets/{id}][%d] getApiV1ProfilesPetsIdUnauthorized %s", 401, payload)
}

func (o *GetAPIV1ProfilesPetsIDUnauthorized) GetPayload() *models.ModelsErrorResponse {
	return o.Payload
}

func (o *GetAPIV1ProfilesPetsIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1ProfilesPetsIDNotFound creates a GetAPIV1ProfilesPetsIDNotFound with default headers values
func NewGetAPIV1ProfilesPetsIDNotFound() *GetAPIV1ProfilesPetsIDNotFound {
	return &GetAPIV1ProfilesPetsIDNotFound{}
}

/*
GetAPIV1ProfilesPetsIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetAPIV1ProfilesPetsIDNotFound struct {
	Payload *models.ModelsErrorResponse
}

// IsSuccess returns true when this get Api v1 profiles pets Id not found response has a 2xx status code
func (o *GetAPIV1ProfilesPetsIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 profiles pets Id not found response has a 3xx status code
func (o *GetAPIV1ProfilesPetsIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 profiles pets Id not found response has a 4xx status code
func (o *GetAPIV1ProfilesPetsIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 profiles pets Id not found response has a 5xx status code
func (o *GetAPIV1ProfilesPetsIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 profiles pets Id not found response a status code equal to that given
func (o *GetAPIV1ProfilesPetsIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Api v1 profiles pets Id not found response
func (o *GetAPIV1ProfilesPetsIDNotFound) Code() int {
	return 404
}

func (o *GetAPIV1ProfilesPetsIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/pets/{id}][%d] getApiV1ProfilesPetsIdNotFound %s", 404, payload)
}

func (o *GetAPIV1ProfilesPetsIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/pets/{id}][%d] getApiV1ProfilesPetsIdNotFound %s", 404, payload)
}

func (o *GetAPIV1ProfilesPetsIDNotFound) GetPayload() *models.ModelsErrorResponse {
	return o.Payload
}

func (o *GetAPIV1ProfilesPetsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1ProfilesPetsIDInternalServerError creates a GetAPIV1ProfilesPetsIDInternalServerError with default headers values
func NewGetAPIV1ProfilesPetsIDInternalServerError() *GetAPIV1ProfilesPetsIDInternalServerError {
	return &GetAPIV1ProfilesPetsIDInternalServerError{}
}

/*
GetAPIV1ProfilesPetsIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetAPIV1ProfilesPetsIDInternalServerError struct {
	Payload *models.ModelsErrorResponse
}

// IsSuccess returns true when this get Api v1 profiles pets Id internal server error response has a 2xx status code
func (o *GetAPIV1ProfilesPetsIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 profiles pets Id internal server error response has a 3xx status code
func (o *GetAPIV1ProfilesPetsIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 profiles pets Id internal server error response has a 4xx status code
func (o *GetAPIV1ProfilesPetsIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 profiles pets Id internal server error response has a 5xx status code
func (o *GetAPIV1ProfilesPetsIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 profiles pets Id internal server error response a status code equal to that given
func (o *GetAPIV1ProfilesPetsIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 profiles pets Id internal server error response
func (o *GetAPIV1ProfilesPetsIDInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1ProfilesPetsIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/pets/{id}][%d] getApiV1ProfilesPetsIdInternalServerError %s", 500, payload)
}

func (o *GetAPIV1ProfilesPetsIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/pets/{id}][%d] getApiV1ProfilesPetsIdInternalServerError %s", 500, payload)
}

func (o *GetAPIV1ProfilesPetsIDInternalServerError) GetPayload() *models.ModelsErrorResponse {
	return o.Payload
}

func (o *GetAPIV1ProfilesPetsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
