// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV1ProfilesPetsParams creates a new GetAPIV1ProfilesPetsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1ProfilesPetsParams() *GetAPIV1ProfilesPetsParams {
	return &GetAPIV1ProfilesPetsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1ProfilesPetsParamsWithTimeout creates a new GetAPIV1ProfilesPetsParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1ProfilesPetsParamsWithTimeout(timeout time.Duration) *GetAPIV1ProfilesPetsParams {
	return &GetAPIV1ProfilesPetsParams{
		timeout: timeout,
	}
}

// NewGetAPIV1ProfilesPetsParamsWithContext creates a new GetAPIV1ProfilesPetsParams object
// with the ability to set a context for a request.
func NewGetAPIV1ProfilesPetsParamsWithContext(ctx context.Context) *GetAPIV1ProfilesPetsParams {
	return &GetAPIV1ProfilesPetsParams{
		Context: ctx,
	}
}

// NewGetAPIV1ProfilesPetsParamsWithHTTPClient creates a new GetAPIV1ProfilesPetsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1ProfilesPetsParamsWithHTTPClient(client *http.Client) *GetAPIV1ProfilesPetsParams {
	return &GetAPIV1ProfilesPetsParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1ProfilesPetsParams contains all the parameters to send to the API endpoint

	for the get API v1 profiles pets operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1ProfilesPetsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 profiles pets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1ProfilesPetsParams) WithDefaults() *GetAPIV1ProfilesPetsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 profiles pets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1ProfilesPetsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v1 profiles pets params
func (o *GetAPIV1ProfilesPetsParams) WithTimeout(timeout time.Duration) *GetAPIV1ProfilesPetsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 profiles pets params
func (o *GetAPIV1ProfilesPetsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 profiles pets params
func (o *GetAPIV1ProfilesPetsParams) WithContext(ctx context.Context) *GetAPIV1ProfilesPetsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 profiles pets params
func (o *GetAPIV1ProfilesPetsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 profiles pets params
func (o *GetAPIV1ProfilesPetsParams) WithHTTPClient(client *http.Client) *GetAPIV1ProfilesPetsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 profiles pets params
func (o *GetAPIV1ProfilesPetsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1ProfilesPetsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
