// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	models "github.com/dreadster3/pawcare/shared/models/profile"
)

// NewPostAPIV1ProfilesPetsParams creates a new PostAPIV1ProfilesPetsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1ProfilesPetsParams() *PostAPIV1ProfilesPetsParams {
	return &PostAPIV1ProfilesPetsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1ProfilesPetsParamsWithTimeout creates a new PostAPIV1ProfilesPetsParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1ProfilesPetsParamsWithTimeout(timeout time.Duration) *PostAPIV1ProfilesPetsParams {
	return &PostAPIV1ProfilesPetsParams{
		timeout: timeout,
	}
}

// NewPostAPIV1ProfilesPetsParamsWithContext creates a new PostAPIV1ProfilesPetsParams object
// with the ability to set a context for a request.
func NewPostAPIV1ProfilesPetsParamsWithContext(ctx context.Context) *PostAPIV1ProfilesPetsParams {
	return &PostAPIV1ProfilesPetsParams{
		Context: ctx,
	}
}

// NewPostAPIV1ProfilesPetsParamsWithHTTPClient creates a new PostAPIV1ProfilesPetsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1ProfilesPetsParamsWithHTTPClient(client *http.Client) *PostAPIV1ProfilesPetsParams {
	return &PostAPIV1ProfilesPetsParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1ProfilesPetsParams contains all the parameters to send to the API endpoint

	for the post API v1 profiles pets operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1ProfilesPetsParams struct {

	/* Request.

	   Pet Profile
	*/
	Request *models.ModelsPet

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 profiles pets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1ProfilesPetsParams) WithDefaults() *PostAPIV1ProfilesPetsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 profiles pets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1ProfilesPetsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 profiles pets params
func (o *PostAPIV1ProfilesPetsParams) WithTimeout(timeout time.Duration) *PostAPIV1ProfilesPetsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 profiles pets params
func (o *PostAPIV1ProfilesPetsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 profiles pets params
func (o *PostAPIV1ProfilesPetsParams) WithContext(ctx context.Context) *PostAPIV1ProfilesPetsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 profiles pets params
func (o *PostAPIV1ProfilesPetsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 profiles pets params
func (o *PostAPIV1ProfilesPetsParams) WithHTTPClient(client *http.Client) *PostAPIV1ProfilesPetsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 profiles pets params
func (o *PostAPIV1ProfilesPetsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post API v1 profiles pets params
func (o *PostAPIV1ProfilesPetsParams) WithRequest(request *models.ModelsPet) *PostAPIV1ProfilesPetsParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post API v1 profiles pets params
func (o *PostAPIV1ProfilesPetsParams) SetRequest(request *models.ModelsPet) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1ProfilesPetsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
