// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "github.com/dreadster3/pawcare/shared/models/profile"
)

// PostAPIV1ProfilesPetsReader is a Reader for the PostAPIV1ProfilesPets structure.
type PostAPIV1ProfilesPetsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1ProfilesPetsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostAPIV1ProfilesPetsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1ProfilesPetsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAPIV1ProfilesPetsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1ProfilesPetsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/profiles/pets] PostAPIV1ProfilesPets", response, response.Code())
	}
}

// NewPostAPIV1ProfilesPetsCreated creates a PostAPIV1ProfilesPetsCreated with default headers values
func NewPostAPIV1ProfilesPetsCreated() *PostAPIV1ProfilesPetsCreated {
	return &PostAPIV1ProfilesPetsCreated{}
}

/*
PostAPIV1ProfilesPetsCreated describes a response with status code 201, with default header values.

Created
*/
type PostAPIV1ProfilesPetsCreated struct {
	Payload *models.ModelsPet
}

// IsSuccess returns true when this post Api v1 profiles pets created response has a 2xx status code
func (o *PostAPIV1ProfilesPetsCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 profiles pets created response has a 3xx status code
func (o *PostAPIV1ProfilesPetsCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 profiles pets created response has a 4xx status code
func (o *PostAPIV1ProfilesPetsCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 profiles pets created response has a 5xx status code
func (o *PostAPIV1ProfilesPetsCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 profiles pets created response a status code equal to that given
func (o *PostAPIV1ProfilesPetsCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the post Api v1 profiles pets created response
func (o *PostAPIV1ProfilesPetsCreated) Code() int {
	return 201
}

func (o *PostAPIV1ProfilesPetsCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/profiles/pets][%d] postApiV1ProfilesPetsCreated %s", 201, payload)
}

func (o *PostAPIV1ProfilesPetsCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/profiles/pets][%d] postApiV1ProfilesPetsCreated %s", 201, payload)
}

func (o *PostAPIV1ProfilesPetsCreated) GetPayload() *models.ModelsPet {
	return o.Payload
}

func (o *PostAPIV1ProfilesPetsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsPet)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV1ProfilesPetsBadRequest creates a PostAPIV1ProfilesPetsBadRequest with default headers values
func NewPostAPIV1ProfilesPetsBadRequest() *PostAPIV1ProfilesPetsBadRequest {
	return &PostAPIV1ProfilesPetsBadRequest{}
}

/*
PostAPIV1ProfilesPetsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostAPIV1ProfilesPetsBadRequest struct {
	Payload *models.ModelsErrorResponse
}

// IsSuccess returns true when this post Api v1 profiles pets bad request response has a 2xx status code
func (o *PostAPIV1ProfilesPetsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 profiles pets bad request response has a 3xx status code
func (o *PostAPIV1ProfilesPetsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 profiles pets bad request response has a 4xx status code
func (o *PostAPIV1ProfilesPetsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 profiles pets bad request response has a 5xx status code
func (o *PostAPIV1ProfilesPetsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 profiles pets bad request response a status code equal to that given
func (o *PostAPIV1ProfilesPetsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v1 profiles pets bad request response
func (o *PostAPIV1ProfilesPetsBadRequest) Code() int {
	return 400
}

func (o *PostAPIV1ProfilesPetsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/profiles/pets][%d] postApiV1ProfilesPetsBadRequest %s", 400, payload)
}

func (o *PostAPIV1ProfilesPetsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/profiles/pets][%d] postApiV1ProfilesPetsBadRequest %s", 400, payload)
}

func (o *PostAPIV1ProfilesPetsBadRequest) GetPayload() *models.ModelsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1ProfilesPetsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV1ProfilesPetsUnauthorized creates a PostAPIV1ProfilesPetsUnauthorized with default headers values
func NewPostAPIV1ProfilesPetsUnauthorized() *PostAPIV1ProfilesPetsUnauthorized {
	return &PostAPIV1ProfilesPetsUnauthorized{}
}

/*
PostAPIV1ProfilesPetsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostAPIV1ProfilesPetsUnauthorized struct {
	Payload *models.ModelsErrorResponse
}

// IsSuccess returns true when this post Api v1 profiles pets unauthorized response has a 2xx status code
func (o *PostAPIV1ProfilesPetsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 profiles pets unauthorized response has a 3xx status code
func (o *PostAPIV1ProfilesPetsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 profiles pets unauthorized response has a 4xx status code
func (o *PostAPIV1ProfilesPetsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 profiles pets unauthorized response has a 5xx status code
func (o *PostAPIV1ProfilesPetsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 profiles pets unauthorized response a status code equal to that given
func (o *PostAPIV1ProfilesPetsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post Api v1 profiles pets unauthorized response
func (o *PostAPIV1ProfilesPetsUnauthorized) Code() int {
	return 401
}

func (o *PostAPIV1ProfilesPetsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/profiles/pets][%d] postApiV1ProfilesPetsUnauthorized %s", 401, payload)
}

func (o *PostAPIV1ProfilesPetsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/profiles/pets][%d] postApiV1ProfilesPetsUnauthorized %s", 401, payload)
}

func (o *PostAPIV1ProfilesPetsUnauthorized) GetPayload() *models.ModelsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1ProfilesPetsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV1ProfilesPetsInternalServerError creates a PostAPIV1ProfilesPetsInternalServerError with default headers values
func NewPostAPIV1ProfilesPetsInternalServerError() *PostAPIV1ProfilesPetsInternalServerError {
	return &PostAPIV1ProfilesPetsInternalServerError{}
}

/*
PostAPIV1ProfilesPetsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostAPIV1ProfilesPetsInternalServerError struct {
	Payload *models.ModelsErrorResponse
}

// IsSuccess returns true when this post Api v1 profiles pets internal server error response has a 2xx status code
func (o *PostAPIV1ProfilesPetsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 profiles pets internal server error response has a 3xx status code
func (o *PostAPIV1ProfilesPetsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 profiles pets internal server error response has a 4xx status code
func (o *PostAPIV1ProfilesPetsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 profiles pets internal server error response has a 5xx status code
func (o *PostAPIV1ProfilesPetsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 profiles pets internal server error response a status code equal to that given
func (o *PostAPIV1ProfilesPetsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 profiles pets internal server error response
func (o *PostAPIV1ProfilesPetsInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1ProfilesPetsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/profiles/pets][%d] postApiV1ProfilesPetsInternalServerError %s", 500, payload)
}

func (o *PostAPIV1ProfilesPetsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/profiles/pets][%d] postApiV1ProfilesPetsInternalServerError %s", 500, payload)
}

func (o *PostAPIV1ProfilesPetsInternalServerError) GetPayload() *models.ModelsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1ProfilesPetsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
