name: profile
services:
  server:
    build:
      context: ../../
      dockerfile: ./services/profile/Dockerfile
    ports:
      - "8000:8080"
    env_file: .env

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: profiles
    restart: always
