name: profile
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      DB_NAME: profiles
      DB_HOST: db
      DB_PORT: 27017
      DB_USER: user
      DB_PASSWORD: password
      JWT_SECRET: jwt_secret

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: profiles
    restart: always
