definitions:
  healthcheck.HealthcheckStatus:
    enum:
    - healthy
    - unhealthy
    - degraded
    type: string
    x-enum-varnames:
    - HealthcheckStatusHealthy
    - HealthcheckStatusUnhealthy
    - HealthcheckStatusDegraded
  healthcheck.JSONHealthcheckReport:
    properties:
      services:
        additionalProperties:
          $ref: '#/definitions/healthcheck.HealthcheckStatus'
        type: object
      status:
        $ref: '#/definitions/healthcheck.HealthcheckStatus'
    type: object
  models.EGender:
    enum:
    - Male
    - Female
    type: string
    x-enum-varnames:
    - EGenderMale
    - EGenderFemale
  models.PetProfile:
    properties:
      breed:
        type: string
      date_of_birth:
        type: integer
      gender:
        $ref: '#/definitions/models.EGender'
      id:
        type: string
      name:
        type: string
      owner_id:
        type: string
      picture:
        $ref: '#/definitions/primitive.Binary'
      species:
        type: string
      weight:
        type: number
    type: object
  primitive.Binary:
    properties:
      data:
        items:
          type: integer
        type: array
      subtype:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/healthcheck:
    get:
      description: Checks if the internal services used by the service are healthy
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/healthcheck.JSONHealthcheckReport'
      summary: Endpoint to check if the service is healthy
      tags:
      - healthcheck
  /api/v1/profiles:
    get:
      description: Get all pet profiles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.PetProfile'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all pet profiles
      tags:
      - pet
    post:
      consumes:
      - application/json
      description: Creates a new pet profile
      parameters:
      - description: Pet Profile
        in: body
        name: pet_profile
        required: true
        schema:
          $ref: '#/definitions/models.PetProfile'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.PetProfile'
        "400":
          description: Reason for failure
          schema:
            type: string
        "500":
          description: Reason for failure
          schema:
            type: string
      summary: Create a new pet profile
      tags:
      - pet
  /api/v1/profiles/{id}:
    get:
      description: Get pet profile by ID
      parameters:
      - description: Pet Profile ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PetProfile'
        "400":
          description: Reason for failure
          schema:
            type: string
        "500":
          description: Reason for failure
          schema:
            type: string
      summary: Get pet profile by ID
      tags:
      - pet
swagger: "2.0"
