// Code generated by go-swagger; DO NOT EDIT.

package owner

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "github.com/dreadster3/pawcare/shared/models/profile"
)

// GetAPIV1ProfilesOwnersReader is a Reader for the GetAPIV1ProfilesOwners structure.
type GetAPIV1ProfilesOwnersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1ProfilesOwnersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1ProfilesOwnersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV1ProfilesOwnersBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAPIV1ProfilesOwnersUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAPIV1ProfilesOwnersNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1ProfilesOwnersInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/profiles/owners] GetAPIV1ProfilesOwners", response, response.Code())
	}
}

// NewGetAPIV1ProfilesOwnersOK creates a GetAPIV1ProfilesOwnersOK with default headers values
func NewGetAPIV1ProfilesOwnersOK() *GetAPIV1ProfilesOwnersOK {
	return &GetAPIV1ProfilesOwnersOK{}
}

/*
GetAPIV1ProfilesOwnersOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIV1ProfilesOwnersOK struct {
	Payload *models.ModelsOwner
}

// IsSuccess returns true when this get Api v1 profiles owners o k response has a 2xx status code
func (o *GetAPIV1ProfilesOwnersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 profiles owners o k response has a 3xx status code
func (o *GetAPIV1ProfilesOwnersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 profiles owners o k response has a 4xx status code
func (o *GetAPIV1ProfilesOwnersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 profiles owners o k response has a 5xx status code
func (o *GetAPIV1ProfilesOwnersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 profiles owners o k response a status code equal to that given
func (o *GetAPIV1ProfilesOwnersOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 profiles owners o k response
func (o *GetAPIV1ProfilesOwnersOK) Code() int {
	return 200
}

func (o *GetAPIV1ProfilesOwnersOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/owners][%d] getApiV1ProfilesOwnersOK %s", 200, payload)
}

func (o *GetAPIV1ProfilesOwnersOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/owners][%d] getApiV1ProfilesOwnersOK %s", 200, payload)
}

func (o *GetAPIV1ProfilesOwnersOK) GetPayload() *models.ModelsOwner {
	return o.Payload
}

func (o *GetAPIV1ProfilesOwnersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsOwner)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1ProfilesOwnersBadRequest creates a GetAPIV1ProfilesOwnersBadRequest with default headers values
func NewGetAPIV1ProfilesOwnersBadRequest() *GetAPIV1ProfilesOwnersBadRequest {
	return &GetAPIV1ProfilesOwnersBadRequest{}
}

/*
GetAPIV1ProfilesOwnersBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetAPIV1ProfilesOwnersBadRequest struct {
	Payload *models.ModelsErrorResponse
}

// IsSuccess returns true when this get Api v1 profiles owners bad request response has a 2xx status code
func (o *GetAPIV1ProfilesOwnersBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 profiles owners bad request response has a 3xx status code
func (o *GetAPIV1ProfilesOwnersBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 profiles owners bad request response has a 4xx status code
func (o *GetAPIV1ProfilesOwnersBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 profiles owners bad request response has a 5xx status code
func (o *GetAPIV1ProfilesOwnersBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 profiles owners bad request response a status code equal to that given
func (o *GetAPIV1ProfilesOwnersBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get Api v1 profiles owners bad request response
func (o *GetAPIV1ProfilesOwnersBadRequest) Code() int {
	return 400
}

func (o *GetAPIV1ProfilesOwnersBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/owners][%d] getApiV1ProfilesOwnersBadRequest %s", 400, payload)
}

func (o *GetAPIV1ProfilesOwnersBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/owners][%d] getApiV1ProfilesOwnersBadRequest %s", 400, payload)
}

func (o *GetAPIV1ProfilesOwnersBadRequest) GetPayload() *models.ModelsErrorResponse {
	return o.Payload
}

func (o *GetAPIV1ProfilesOwnersBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1ProfilesOwnersUnauthorized creates a GetAPIV1ProfilesOwnersUnauthorized with default headers values
func NewGetAPIV1ProfilesOwnersUnauthorized() *GetAPIV1ProfilesOwnersUnauthorized {
	return &GetAPIV1ProfilesOwnersUnauthorized{}
}

/*
GetAPIV1ProfilesOwnersUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAPIV1ProfilesOwnersUnauthorized struct {
	Payload *models.ModelsErrorResponse
}

// IsSuccess returns true when this get Api v1 profiles owners unauthorized response has a 2xx status code
func (o *GetAPIV1ProfilesOwnersUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 profiles owners unauthorized response has a 3xx status code
func (o *GetAPIV1ProfilesOwnersUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 profiles owners unauthorized response has a 4xx status code
func (o *GetAPIV1ProfilesOwnersUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 profiles owners unauthorized response has a 5xx status code
func (o *GetAPIV1ProfilesOwnersUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 profiles owners unauthorized response a status code equal to that given
func (o *GetAPIV1ProfilesOwnersUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get Api v1 profiles owners unauthorized response
func (o *GetAPIV1ProfilesOwnersUnauthorized) Code() int {
	return 401
}

func (o *GetAPIV1ProfilesOwnersUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/owners][%d] getApiV1ProfilesOwnersUnauthorized %s", 401, payload)
}

func (o *GetAPIV1ProfilesOwnersUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/owners][%d] getApiV1ProfilesOwnersUnauthorized %s", 401, payload)
}

func (o *GetAPIV1ProfilesOwnersUnauthorized) GetPayload() *models.ModelsErrorResponse {
	return o.Payload
}

func (o *GetAPIV1ProfilesOwnersUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1ProfilesOwnersNotFound creates a GetAPIV1ProfilesOwnersNotFound with default headers values
func NewGetAPIV1ProfilesOwnersNotFound() *GetAPIV1ProfilesOwnersNotFound {
	return &GetAPIV1ProfilesOwnersNotFound{}
}

/*
GetAPIV1ProfilesOwnersNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetAPIV1ProfilesOwnersNotFound struct {
	Payload *models.ModelsErrorResponse
}

// IsSuccess returns true when this get Api v1 profiles owners not found response has a 2xx status code
func (o *GetAPIV1ProfilesOwnersNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 profiles owners not found response has a 3xx status code
func (o *GetAPIV1ProfilesOwnersNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 profiles owners not found response has a 4xx status code
func (o *GetAPIV1ProfilesOwnersNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 profiles owners not found response has a 5xx status code
func (o *GetAPIV1ProfilesOwnersNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 profiles owners not found response a status code equal to that given
func (o *GetAPIV1ProfilesOwnersNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Api v1 profiles owners not found response
func (o *GetAPIV1ProfilesOwnersNotFound) Code() int {
	return 404
}

func (o *GetAPIV1ProfilesOwnersNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/owners][%d] getApiV1ProfilesOwnersNotFound %s", 404, payload)
}

func (o *GetAPIV1ProfilesOwnersNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/owners][%d] getApiV1ProfilesOwnersNotFound %s", 404, payload)
}

func (o *GetAPIV1ProfilesOwnersNotFound) GetPayload() *models.ModelsErrorResponse {
	return o.Payload
}

func (o *GetAPIV1ProfilesOwnersNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1ProfilesOwnersInternalServerError creates a GetAPIV1ProfilesOwnersInternalServerError with default headers values
func NewGetAPIV1ProfilesOwnersInternalServerError() *GetAPIV1ProfilesOwnersInternalServerError {
	return &GetAPIV1ProfilesOwnersInternalServerError{}
}

/*
GetAPIV1ProfilesOwnersInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetAPIV1ProfilesOwnersInternalServerError struct {
	Payload *models.ModelsErrorResponse
}

// IsSuccess returns true when this get Api v1 profiles owners internal server error response has a 2xx status code
func (o *GetAPIV1ProfilesOwnersInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 profiles owners internal server error response has a 3xx status code
func (o *GetAPIV1ProfilesOwnersInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 profiles owners internal server error response has a 4xx status code
func (o *GetAPIV1ProfilesOwnersInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 profiles owners internal server error response has a 5xx status code
func (o *GetAPIV1ProfilesOwnersInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 profiles owners internal server error response a status code equal to that given
func (o *GetAPIV1ProfilesOwnersInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 profiles owners internal server error response
func (o *GetAPIV1ProfilesOwnersInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1ProfilesOwnersInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/owners][%d] getApiV1ProfilesOwnersInternalServerError %s", 500, payload)
}

func (o *GetAPIV1ProfilesOwnersInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/profiles/owners][%d] getApiV1ProfilesOwnersInternalServerError %s", 500, payload)
}

func (o *GetAPIV1ProfilesOwnersInternalServerError) GetPayload() *models.ModelsErrorResponse {
	return o.Payload
}

func (o *GetAPIV1ProfilesOwnersInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
