// Code generated by go-swagger; DO NOT EDIT.

package owner

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV1ProfilesOwnersParams creates a new GetAPIV1ProfilesOwnersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1ProfilesOwnersParams() *GetAPIV1ProfilesOwnersParams {
	return &GetAPIV1ProfilesOwnersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1ProfilesOwnersParamsWithTimeout creates a new GetAPIV1ProfilesOwnersParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1ProfilesOwnersParamsWithTimeout(timeout time.Duration) *GetAPIV1ProfilesOwnersParams {
	return &GetAPIV1ProfilesOwnersParams{
		timeout: timeout,
	}
}

// NewGetAPIV1ProfilesOwnersParamsWithContext creates a new GetAPIV1ProfilesOwnersParams object
// with the ability to set a context for a request.
func NewGetAPIV1ProfilesOwnersParamsWithContext(ctx context.Context) *GetAPIV1ProfilesOwnersParams {
	return &GetAPIV1ProfilesOwnersParams{
		Context: ctx,
	}
}

// NewGetAPIV1ProfilesOwnersParamsWithHTTPClient creates a new GetAPIV1ProfilesOwnersParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1ProfilesOwnersParamsWithHTTPClient(client *http.Client) *GetAPIV1ProfilesOwnersParams {
	return &GetAPIV1ProfilesOwnersParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1ProfilesOwnersParams contains all the parameters to send to the API endpoint

	for the get API v1 profiles owners operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1ProfilesOwnersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 profiles owners params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1ProfilesOwnersParams) WithDefaults() *GetAPIV1ProfilesOwnersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 profiles owners params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1ProfilesOwnersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v1 profiles owners params
func (o *GetAPIV1ProfilesOwnersParams) WithTimeout(timeout time.Duration) *GetAPIV1ProfilesOwnersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 profiles owners params
func (o *GetAPIV1ProfilesOwnersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 profiles owners params
func (o *GetAPIV1ProfilesOwnersParams) WithContext(ctx context.Context) *GetAPIV1ProfilesOwnersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 profiles owners params
func (o *GetAPIV1ProfilesOwnersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 profiles owners params
func (o *GetAPIV1ProfilesOwnersParams) WithHTTPClient(client *http.Client) *GetAPIV1ProfilesOwnersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 profiles owners params
func (o *GetAPIV1ProfilesOwnersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1ProfilesOwnersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
