// Code generated by go-swagger; DO NOT EDIT.

package owner

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "github.com/dreadster3/pawcare/shared/models/profile"
)

// PostAPIV1ProfilesOwnersReader is a Reader for the PostAPIV1ProfilesOwners structure.
type PostAPIV1ProfilesOwnersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1ProfilesOwnersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostAPIV1ProfilesOwnersCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1ProfilesOwnersBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAPIV1ProfilesOwnersUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1ProfilesOwnersInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/profiles/owners] PostAPIV1ProfilesOwners", response, response.Code())
	}
}

// NewPostAPIV1ProfilesOwnersCreated creates a PostAPIV1ProfilesOwnersCreated with default headers values
func NewPostAPIV1ProfilesOwnersCreated() *PostAPIV1ProfilesOwnersCreated {
	return &PostAPIV1ProfilesOwnersCreated{}
}

/*
PostAPIV1ProfilesOwnersCreated describes a response with status code 201, with default header values.

Created
*/
type PostAPIV1ProfilesOwnersCreated struct {
	Payload *models.ModelsOwner
}

// IsSuccess returns true when this post Api v1 profiles owners created response has a 2xx status code
func (o *PostAPIV1ProfilesOwnersCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 profiles owners created response has a 3xx status code
func (o *PostAPIV1ProfilesOwnersCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 profiles owners created response has a 4xx status code
func (o *PostAPIV1ProfilesOwnersCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 profiles owners created response has a 5xx status code
func (o *PostAPIV1ProfilesOwnersCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 profiles owners created response a status code equal to that given
func (o *PostAPIV1ProfilesOwnersCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the post Api v1 profiles owners created response
func (o *PostAPIV1ProfilesOwnersCreated) Code() int {
	return 201
}

func (o *PostAPIV1ProfilesOwnersCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/profiles/owners][%d] postApiV1ProfilesOwnersCreated %s", 201, payload)
}

func (o *PostAPIV1ProfilesOwnersCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/profiles/owners][%d] postApiV1ProfilesOwnersCreated %s", 201, payload)
}

func (o *PostAPIV1ProfilesOwnersCreated) GetPayload() *models.ModelsOwner {
	return o.Payload
}

func (o *PostAPIV1ProfilesOwnersCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsOwner)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV1ProfilesOwnersBadRequest creates a PostAPIV1ProfilesOwnersBadRequest with default headers values
func NewPostAPIV1ProfilesOwnersBadRequest() *PostAPIV1ProfilesOwnersBadRequest {
	return &PostAPIV1ProfilesOwnersBadRequest{}
}

/*
PostAPIV1ProfilesOwnersBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostAPIV1ProfilesOwnersBadRequest struct {
	Payload *models.ModelsErrorResponse
}

// IsSuccess returns true when this post Api v1 profiles owners bad request response has a 2xx status code
func (o *PostAPIV1ProfilesOwnersBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 profiles owners bad request response has a 3xx status code
func (o *PostAPIV1ProfilesOwnersBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 profiles owners bad request response has a 4xx status code
func (o *PostAPIV1ProfilesOwnersBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 profiles owners bad request response has a 5xx status code
func (o *PostAPIV1ProfilesOwnersBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 profiles owners bad request response a status code equal to that given
func (o *PostAPIV1ProfilesOwnersBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v1 profiles owners bad request response
func (o *PostAPIV1ProfilesOwnersBadRequest) Code() int {
	return 400
}

func (o *PostAPIV1ProfilesOwnersBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/profiles/owners][%d] postApiV1ProfilesOwnersBadRequest %s", 400, payload)
}

func (o *PostAPIV1ProfilesOwnersBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/profiles/owners][%d] postApiV1ProfilesOwnersBadRequest %s", 400, payload)
}

func (o *PostAPIV1ProfilesOwnersBadRequest) GetPayload() *models.ModelsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1ProfilesOwnersBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV1ProfilesOwnersUnauthorized creates a PostAPIV1ProfilesOwnersUnauthorized with default headers values
func NewPostAPIV1ProfilesOwnersUnauthorized() *PostAPIV1ProfilesOwnersUnauthorized {
	return &PostAPIV1ProfilesOwnersUnauthorized{}
}

/*
PostAPIV1ProfilesOwnersUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostAPIV1ProfilesOwnersUnauthorized struct {
	Payload *models.ModelsErrorResponse
}

// IsSuccess returns true when this post Api v1 profiles owners unauthorized response has a 2xx status code
func (o *PostAPIV1ProfilesOwnersUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 profiles owners unauthorized response has a 3xx status code
func (o *PostAPIV1ProfilesOwnersUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 profiles owners unauthorized response has a 4xx status code
func (o *PostAPIV1ProfilesOwnersUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 profiles owners unauthorized response has a 5xx status code
func (o *PostAPIV1ProfilesOwnersUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 profiles owners unauthorized response a status code equal to that given
func (o *PostAPIV1ProfilesOwnersUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post Api v1 profiles owners unauthorized response
func (o *PostAPIV1ProfilesOwnersUnauthorized) Code() int {
	return 401
}

func (o *PostAPIV1ProfilesOwnersUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/profiles/owners][%d] postApiV1ProfilesOwnersUnauthorized %s", 401, payload)
}

func (o *PostAPIV1ProfilesOwnersUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/profiles/owners][%d] postApiV1ProfilesOwnersUnauthorized %s", 401, payload)
}

func (o *PostAPIV1ProfilesOwnersUnauthorized) GetPayload() *models.ModelsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1ProfilesOwnersUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV1ProfilesOwnersInternalServerError creates a PostAPIV1ProfilesOwnersInternalServerError with default headers values
func NewPostAPIV1ProfilesOwnersInternalServerError() *PostAPIV1ProfilesOwnersInternalServerError {
	return &PostAPIV1ProfilesOwnersInternalServerError{}
}

/*
PostAPIV1ProfilesOwnersInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostAPIV1ProfilesOwnersInternalServerError struct {
	Payload *models.ModelsErrorResponse
}

// IsSuccess returns true when this post Api v1 profiles owners internal server error response has a 2xx status code
func (o *PostAPIV1ProfilesOwnersInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 profiles owners internal server error response has a 3xx status code
func (o *PostAPIV1ProfilesOwnersInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 profiles owners internal server error response has a 4xx status code
func (o *PostAPIV1ProfilesOwnersInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 profiles owners internal server error response has a 5xx status code
func (o *PostAPIV1ProfilesOwnersInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 profiles owners internal server error response a status code equal to that given
func (o *PostAPIV1ProfilesOwnersInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 profiles owners internal server error response
func (o *PostAPIV1ProfilesOwnersInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1ProfilesOwnersInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/profiles/owners][%d] postApiV1ProfilesOwnersInternalServerError %s", 500, payload)
}

func (o *PostAPIV1ProfilesOwnersInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/profiles/owners][%d] postApiV1ProfilesOwnersInternalServerError %s", 500, payload)
}

func (o *PostAPIV1ProfilesOwnersInternalServerError) GetPayload() *models.ModelsErrorResponse {
	return o.Payload
}

func (o *PostAPIV1ProfilesOwnersInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModelsErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
