// Code generated by go-swagger; DO NOT EDIT.

package owner

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	models "github.com/dreadster3/pawcare/shared/models/profile"
)

// NewPostAPIV1ProfilesOwnersParams creates a new PostAPIV1ProfilesOwnersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1ProfilesOwnersParams() *PostAPIV1ProfilesOwnersParams {
	return &PostAPIV1ProfilesOwnersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1ProfilesOwnersParamsWithTimeout creates a new PostAPIV1ProfilesOwnersParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1ProfilesOwnersParamsWithTimeout(timeout time.Duration) *PostAPIV1ProfilesOwnersParams {
	return &PostAPIV1ProfilesOwnersParams{
		timeout: timeout,
	}
}

// NewPostAPIV1ProfilesOwnersParamsWithContext creates a new PostAPIV1ProfilesOwnersParams object
// with the ability to set a context for a request.
func NewPostAPIV1ProfilesOwnersParamsWithContext(ctx context.Context) *PostAPIV1ProfilesOwnersParams {
	return &PostAPIV1ProfilesOwnersParams{
		Context: ctx,
	}
}

// NewPostAPIV1ProfilesOwnersParamsWithHTTPClient creates a new PostAPIV1ProfilesOwnersParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1ProfilesOwnersParamsWithHTTPClient(client *http.Client) *PostAPIV1ProfilesOwnersParams {
	return &PostAPIV1ProfilesOwnersParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1ProfilesOwnersParams contains all the parameters to send to the API endpoint

	for the post API v1 profiles owners operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1ProfilesOwnersParams struct {

	/* Request.

	   Owner Profile
	*/
	Request *models.ModelsOwner

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 profiles owners params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1ProfilesOwnersParams) WithDefaults() *PostAPIV1ProfilesOwnersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 profiles owners params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1ProfilesOwnersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 profiles owners params
func (o *PostAPIV1ProfilesOwnersParams) WithTimeout(timeout time.Duration) *PostAPIV1ProfilesOwnersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 profiles owners params
func (o *PostAPIV1ProfilesOwnersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 profiles owners params
func (o *PostAPIV1ProfilesOwnersParams) WithContext(ctx context.Context) *PostAPIV1ProfilesOwnersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 profiles owners params
func (o *PostAPIV1ProfilesOwnersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 profiles owners params
func (o *PostAPIV1ProfilesOwnersParams) WithHTTPClient(client *http.Client) *PostAPIV1ProfilesOwnersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 profiles owners params
func (o *PostAPIV1ProfilesOwnersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post API v1 profiles owners params
func (o *PostAPIV1ProfilesOwnersParams) WithRequest(request *models.ModelsOwner) *PostAPIV1ProfilesOwnersParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post API v1 profiles owners params
func (o *PostAPIV1ProfilesOwnersParams) SetRequest(request *models.ModelsOwner) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1ProfilesOwnersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
