// Code generated by go-swagger; DO NOT EDIT.

package healthcheck

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIHealthcheckParams creates a new GetAPIHealthcheckParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIHealthcheckParams() *GetAPIHealthcheckParams {
	return &GetAPIHealthcheckParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIHealthcheckParamsWithTimeout creates a new GetAPIHealthcheckParams object
// with the ability to set a timeout on a request.
func NewGetAPIHealthcheckParamsWithTimeout(timeout time.Duration) *GetAPIHealthcheckParams {
	return &GetAPIHealthcheckParams{
		timeout: timeout,
	}
}

// NewGetAPIHealthcheckParamsWithContext creates a new GetAPIHealthcheckParams object
// with the ability to set a context for a request.
func NewGetAPIHealthcheckParamsWithContext(ctx context.Context) *GetAPIHealthcheckParams {
	return &GetAPIHealthcheckParams{
		Context: ctx,
	}
}

// NewGetAPIHealthcheckParamsWithHTTPClient creates a new GetAPIHealthcheckParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIHealthcheckParamsWithHTTPClient(client *http.Client) *GetAPIHealthcheckParams {
	return &GetAPIHealthcheckParams{
		HTTPClient: client,
	}
}

/*
GetAPIHealthcheckParams contains all the parameters to send to the API endpoint

	for the get API healthcheck operation.

	Typically these are written to a http.Request.
*/
type GetAPIHealthcheckParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API healthcheck params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIHealthcheckParams) WithDefaults() *GetAPIHealthcheckParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API healthcheck params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIHealthcheckParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API healthcheck params
func (o *GetAPIHealthcheckParams) WithTimeout(timeout time.Duration) *GetAPIHealthcheckParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API healthcheck params
func (o *GetAPIHealthcheckParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API healthcheck params
func (o *GetAPIHealthcheckParams) WithContext(ctx context.Context) *GetAPIHealthcheckParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API healthcheck params
func (o *GetAPIHealthcheckParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API healthcheck params
func (o *GetAPIHealthcheckParams) WithHTTPClient(client *http.Client) *GetAPIHealthcheckParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API healthcheck params
func (o *GetAPIHealthcheckParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIHealthcheckParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
