// Code generated by go-swagger; DO NOT EDIT.

package healthcheck

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "github.com/dreadster3/pawcare/shared/models/profile"
)

// GetAPIHealthcheckReader is a Reader for the GetAPIHealthcheck structure.
type GetAPIHealthcheckReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIHealthcheckReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIHealthcheckOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/healthcheck] GetAPIHealthcheck", response, response.Code())
	}
}

// NewGetAPIHealthcheckOK creates a GetAPIHealthcheckOK with default headers values
func NewGetAPIHealthcheckOK() *GetAPIHealthcheckOK {
	return &GetAPIHealthcheckOK{}
}

/*
GetAPIHealthcheckOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIHealthcheckOK struct {
	Payload *models.HealthcheckJSONHealthcheckReport
}

// IsSuccess returns true when this get Api healthcheck o k response has a 2xx status code
func (o *GetAPIHealthcheckOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api healthcheck o k response has a 3xx status code
func (o *GetAPIHealthcheckOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api healthcheck o k response has a 4xx status code
func (o *GetAPIHealthcheckOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api healthcheck o k response has a 5xx status code
func (o *GetAPIHealthcheckOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api healthcheck o k response a status code equal to that given
func (o *GetAPIHealthcheckOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api healthcheck o k response
func (o *GetAPIHealthcheckOK) Code() int {
	return 200
}

func (o *GetAPIHealthcheckOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/healthcheck][%d] getApiHealthcheckOK %s", 200, payload)
}

func (o *GetAPIHealthcheckOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/healthcheck][%d] getApiHealthcheckOK %s", 200, payload)
}

func (o *GetAPIHealthcheckOK) GetPayload() *models.HealthcheckJSONHealthcheckReport {
	return o.Payload
}

func (o *GetAPIHealthcheckOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HealthcheckJSONHealthcheckReport)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
